// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumeAccountRateLimitResetCreditOutcome } from "./ConsumeAccountRateLimitResetCreditOutcome";
import type { UsageResetCompletion } from "./UsageResetCompletion";

export type ConsumeAccountRateLimitResetCreditResponse = { resetCompletion: UsageResetCompletion | null, outcome: ConsumeAccountRateLimitResetCreditOutcome, };
