// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceNativeSource } from "./InferenceNativeSource";

/**
 * Discovery or the current native login cannot establish which account served a request.
 */
export type InferenceAttribution = { "type": "servedNative", source: InferenceNativeSource, accountId: string, } | { "type": "intendedNative", source: InferenceNativeSource, accountId: string, } | { "type": "claude" } | { "type": "unknown" };
