// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceAttribution } from "./InferenceAttribution";

/**
 * Scope for rolling inference quota; native account maintenance remains unscoped.
 */
export type InferenceScope = { threadId: string, turnId: string, attribution: InferenceAttribution, };
