// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceNativeSource } from "./InferenceNativeSource";

/**
 * An existing live wait's exact native source; this read never changes account selection.
 */
export type UsageResetTargetParams = { threadId: string, turnId: string, source: InferenceNativeSource, accountId: string,
/**
 * Earliest eligible completion, in Unix seconds on the inference host.
 */
failedAt: number,
/**
 * When supplied, admission requires this exact durable completion.
 */
completionId?: string | null, };
