// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceNativeSource } from "./InferenceNativeSource";

export type UsageResetCompletion = { id: string, source: InferenceNativeSource, accountId: string,
/**
 * Unix seconds; does not prove present quota or proxy readiness.
 */
completedAt: number, };
